repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path, pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        entry: pflake8
        # We use a custom version of flake8 that includes a fix for Python 3.12 compatibility
        additional_dependencies: ["git+https://github.com/neptune-ai/pyproject-flake8.git@7.0.0"]
default_language_version:
    python: python3
