---
name: Test Integration
description: Check unit tests
inputs:
  python-version:
    description: "Python version"
    required: true
  os:
    description: "Operating system"
    required: true
  report_job:
    description: "Job name to update by JUnit report"
    required: true
  working_directory:
    description: 'Working directory'
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - name: Test
      working-directory: ${{ inputs.working_directory }}
      run: |
        pytest -v -n 2 ./tests/integration/ \
        --timeout=120 --timeout_method=thread \
        --color=yes \
        --junitxml="${{ inputs.working_directory }}/test-results/test-integration-${{ inputs.os }}-${{ inputs.python-version }}.xml"
      shell: bash

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-artifacts
        path: ${{ inputs.working_directory }}/test-results

    - name: Report
      uses: mikepenz/action-junit-report@v3.6.2
      if: always()
      with:
        report_paths: "${{ inputs.working_directory }}/test-results/test-integration-*.xml"
        update_check: true
        include_passed: true
        annotate_notice: true
        job_name: ${{ inputs.report_job }}
