"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ProtoSeriesValuesResponseDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SERIES_FIELD_NUMBER: builtins.int

    @property
    def series(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtoSeriesValuesSingleSeriesResponseDTO]:
        ...

    def __init__(self, *, series: collections.abc.Iterable[global___ProtoSeriesValuesSingleSeriesResponseDTO] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['series', b'series']) -> None:
        ...
global___ProtoSeriesValuesResponseDTO = ProtoSeriesValuesResponseDTO

class ProtoSeriesValuesSingleSeriesResponseDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTID_FIELD_NUMBER: builtins.int
    SEARCHAFTER_FIELD_NUMBER: builtins.int
    STRING_SERIES_FIELD_NUMBER: builtins.int
    SERIESVALUES_FIELD_NUMBER: builtins.int
    requestId: builtins.str

    @property
    def searchAfter(self) -> global___ProtoSeriesValuesSearchAfterDTO:
        ...

    @property
    def string_series(self) -> global___ProtoSeriesValuesDTO:
        """deprecated"""

    @property
    def seriesValues(self) -> global___ProtoSeriesValuesDTO:
        ...

    def __init__(self, *, requestId: builtins.str=..., searchAfter: global___ProtoSeriesValuesSearchAfterDTO | None=..., string_series: global___ProtoSeriesValuesDTO | None=..., seriesValues: global___ProtoSeriesValuesDTO | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['_searchAfter', b'_searchAfter', 'searchAfter', b'searchAfter', 'series', b'series', 'seriesValues', b'seriesValues', 'string_series', b'string_series']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['_searchAfter', b'_searchAfter', 'requestId', b'requestId', 'searchAfter', b'searchAfter', 'series', b'series', 'seriesValues', b'seriesValues', 'string_series', b'string_series']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['_searchAfter', b'_searchAfter']) -> typing_extensions.Literal['searchAfter'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['series', b'series']) -> typing_extensions.Literal['string_series', 'seriesValues'] | None:
        ...
global___ProtoSeriesValuesSingleSeriesResponseDTO = ProtoSeriesValuesSingleSeriesResponseDTO

class ProtoSeriesValuesSearchAfterDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FINISHED_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    finished: builtins.bool
    token: builtins.str

    def __init__(self, *, finished: builtins.bool=..., token: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['finished', b'finished', 'token', b'token']) -> None:
        ...
global___ProtoSeriesValuesSearchAfterDTO = ProtoSeriesValuesSearchAfterDTO

class ProtoFloatSeriesValuesResponseDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SERIES_FIELD_NUMBER: builtins.int

    @property
    def series(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtoFloatSeriesValuesSingleSeriesResponseDTO]:
        ...

    def __init__(self, *, series: collections.abc.Iterable[global___ProtoFloatSeriesValuesSingleSeriesResponseDTO] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['series', b'series']) -> None:
        ...
global___ProtoFloatSeriesValuesResponseDTO = ProtoFloatSeriesValuesResponseDTO

class ProtoFloatSeriesValuesSingleSeriesResponseDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REQUESTID_FIELD_NUMBER: builtins.int
    SERIES_FIELD_NUMBER: builtins.int
    requestId: builtins.str

    @property
    def series(self) -> global___ProtoFloatSeriesValuesDTO:
        ...

    def __init__(self, *, requestId: builtins.str=..., series: global___ProtoFloatSeriesValuesDTO | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['series', b'series']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['requestId', b'requestId', 'series', b'series']) -> None:
        ...
global___ProtoFloatSeriesValuesSingleSeriesResponseDTO = ProtoFloatSeriesValuesSingleSeriesResponseDTO

class ProtoFloatSeriesValuesDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOTAL_ITEM_COUNT_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    total_item_count: builtins.int

    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtoFloatPointValueDTO]:
        ...

    def __init__(self, *, total_item_count: builtins.int=..., values: collections.abc.Iterable[global___ProtoFloatPointValueDTO] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['total_item_count', b'total_item_count', 'values', b'values']) -> None:
        ...
global___ProtoFloatSeriesValuesDTO = ProtoFloatSeriesValuesDTO

class ProtoFloatPointValueDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESTAMP_MILLIS_FIELD_NUMBER: builtins.int
    STEP_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    IS_PREVIEW_FIELD_NUMBER: builtins.int
    COMPLETION_RATIO_FIELD_NUMBER: builtins.int
    timestamp_millis: builtins.int
    step: builtins.float
    value: builtins.float
    is_preview: builtins.bool
    completion_ratio: builtins.float

    def __init__(self, *, timestamp_millis: builtins.int=..., step: builtins.float=..., value: builtins.float=..., is_preview: builtins.bool=..., completion_ratio: builtins.float=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['completion_ratio', b'completion_ratio', 'is_preview', b'is_preview', 'step', b'step', 'timestamp_millis', b'timestamp_millis', 'value', b'value']) -> None:
        ...
global___ProtoFloatPointValueDTO = ProtoFloatPointValueDTO

class ProtoSeriesValuesDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUES_FIELD_NUMBER: builtins.int

    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProtoPointValueDTO]:
        ...

    def __init__(self, *, values: collections.abc.Iterable[global___ProtoPointValueDTO] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['values', b'values']) -> None:
        ...
global___ProtoSeriesValuesDTO = ProtoSeriesValuesDTO

class ProtoPointValueDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESTAMP_MILLIS_FIELD_NUMBER: builtins.int
    STEP_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    IS_PREVIEW_FIELD_NUMBER: builtins.int
    COMPLETION_RATIO_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    timestamp_millis: builtins.int
    step: builtins.float
    value: builtins.str
    'deprecated'
    is_preview: builtins.bool
    completion_ratio: builtins.float

    @property
    def object(self) -> global___ProtoSeriesPointValueObjectDTO:
        ...

    def __init__(self, *, timestamp_millis: builtins.int=..., step: builtins.float=..., value: builtins.str | None=..., is_preview: builtins.bool=..., completion_ratio: builtins.float=..., object: global___ProtoSeriesPointValueObjectDTO | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['_object', b'_object', '_value', b'_value', 'object', b'object', 'value', b'value']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['_object', b'_object', '_value', b'_value', 'completion_ratio', b'completion_ratio', 'is_preview', b'is_preview', 'object', b'object', 'step', b'step', 'timestamp_millis', b'timestamp_millis', 'value', b'value']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['_object', b'_object']) -> typing_extensions.Literal['object'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal['_value', b'_value']) -> typing_extensions.Literal['value'] | None:
        ...
global___ProtoPointValueDTO = ProtoPointValueDTO

class ProtoSeriesPointValueObjectDTO(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STRINGVALUE_FIELD_NUMBER: builtins.int
    HISTOGRAM_FIELD_NUMBER: builtins.int
    FILEREF_FIELD_NUMBER: builtins.int
    stringValue: builtins.str

    @property
    def histogram(self) -> global___ProtoHistogram:
        ...

    @property
    def fileRef(self) -> global___ProtoFileRef:
        ...

    def __init__(self, *, stringValue: builtins.str=..., histogram: global___ProtoHistogram | None=..., fileRef: global___ProtoFileRef | None=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['fileRef', b'fileRef', 'histogram', b'histogram', 'stringValue', b'stringValue', 'value', b'value']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['fileRef', b'fileRef', 'histogram', b'histogram', 'stringValue', b'stringValue', 'value', b'value']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['value', b'value']) -> typing_extensions.Literal['stringValue', 'histogram', 'fileRef'] | None:
        ...
global___ProtoSeriesPointValueObjectDTO = ProtoSeriesPointValueObjectDTO

class ProtoHistogram(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    EDGES_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    type: builtins.str

    @property
    def edges(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        ...

    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        ...

    def __init__(self, *, type: builtins.str=..., edges: collections.abc.Iterable[builtins.float] | None=..., values: collections.abc.Iterable[builtins.float] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['edges', b'edges', 'type', b'type', 'values', b'values']) -> None:
        ...
global___ProtoHistogram = ProtoHistogram

class ProtoFileRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_FIELD_NUMBER: builtins.int
    SIZEBYTES_FIELD_NUMBER: builtins.int
    MIMETYPE_FIELD_NUMBER: builtins.int
    path: builtins.str
    sizeBytes: builtins.int
    mimeType: builtins.str

    def __init__(self, *, path: builtins.str=..., sizeBytes: builtins.int=..., mimeType: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['mimeType', b'mimeType', 'path', b'path', 'sizeBytes', b'sizeBytes']) -> None:
        ...
global___ProtoFileRef = ProtoFileRef