---
name: Package
description: Install python and package
inputs:
  python-version:
    description: "Python version"
    required: true
  os:
    description: "Operating system"
    required: true
  working_directory:
    description: "Working directory"
    required: false
    default: .

runs:
    using: "composite"
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: neptune-ai/neptune-fetcher
          path: ${{ inputs.working_directory }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: |
          uv pip install -r ./dev_requirements.txt
        shell: bash

      - name: List dependencies
        run: |
          uv pip list
        shell: bash
