name: Run e2e tests

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt

      - name: Run tests
        env:
          NEPTUNE_WORKSPACE: ${{ secrets.E2E_WORKSPACE }}
          NEPTUNE_API_TOKEN: ${{ secrets.E2E_API_TOKEN }}
        run: bash .github/scripts/run-e2e-tests.sh

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-artifacts
          path: "./test-results/"

      - name: Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "./test-results/test-e2e*.xml"
          update_check: true
          include_passed: true
          annotate_notice: true
          job_name: "e2e tests"
