name: Run e2e tests - neptune-fetcher

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/.*
  pull_request: # Don't run e2e tests on PRs that don't modify source code
    paths:
      - 'neptune_fetcher/src/**'
      - 'neptune_fetcher/tests/**'
      - 'dev_requirements.txt'
      - 'neptune_fetcher/pyproject.toml'
      - '.github/workflows/tests-e2e-fetcher.yml'

jobs:
  test:
    runs-on: tools-gha-runners
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd neptune_fetcher &&
          python -m pip install --upgrade pip &&
          pip install -r dev_requirements.txt

      - name: Run tests
        env:
          NEPTUNE_WORKSPACE: ${{ secrets.E2E_WORKSPACE }}
          NEPTUNE_E2E_WORKSPACE: ${{ secrets.E2E_WORKSPACE }}
          NEPTUNE_E2E_PROJECT: ${{ secrets.E2E_PROJECT }}
          NEPTUNE_API_TOKEN: ${{ secrets.E2E_API_TOKEN }}
          PROJECT_DIR: neptune_fetcher
          TESTS_DIR: tests/e2e
        run: bash .github/scripts/run-e2e-tests.sh

      - name: Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "./neptune_fetcher/test-results/test-e2e*.xml"
          update_check: true
          include_passed: true
          annotate_notice: true
          job_name: "e2e tests"

      - name: Notify Slack on failure
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const webhookUrl = process.env.SLACK_WEBHOOK_URL;
            const payload = {
              username: "GitHub Actions",
              text: `E2E tests failed in the repository: <https://github.com/${context.repo.owner}/${context.repo.repo}|${context.repo.owner}/${context.repo.repo}>. Please check the details.`
            };
            await fetch(webhookUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(payload)
            });
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
