name: Run package tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-neptune:
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu" ]
        python-version: [ "3.13" ]

        neptune-version: [ "2.0.0a9", "2.0.0a8", "2.0.0a7", "2.0.0a6", "2.0.0a5", "2.0.0a4", "2.0.0a3", "2.0.0a2" ]

    name: 'package test (neptune==${{ matrix.neptune-version }}, fetcher==.)'
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install . neptune==${{ matrix.neptune-version }} "pytest" "pytest-timeout" "pytest-xdist"
        shell: bash

      - name: List dependencies
        run: |
          pip list
        shell: bash
      - name: Import neptune then neptune-fetcher
        run: |
          python -c "import neptune; import neptune_fetcher;  print('Hello, world!')"
        shell: bash

      - name: Import neptune-fetcher then neptune
        run: |
          python -c "import neptune_fetcher; import neptune;  print('Hello, world!')"
        shell: bash

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          test-directory: package
          report-job: 'test (${{ matrix.os }} - py${{ matrix.python-version }}) - neptune==${{ matrix.neptune-version }}'
          report-suffix: 'package-${{ matrix.python-version }}-${{ matrix.os }}-${{ matrix.neptune-version }}'
