name: Run unit tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'dev_requirements.txt'
      - 'pyproject.toml'
  push:
    branches:
      - main
      - dev/.*

jobs:
  test:
    timeout-minutes: 75
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.13" ]
        os: [ ubuntu, macos, windows ]

    name: 'unit test (${{ matrix.os }} - py${{ matrix.python-version }})'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Install package
        uses: ./.github/actions/install-package
        with:
          working_directory: .
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}-latest

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          working-directory: .
          test-directory: unit
          report-job: 'test (${{ matrix.os }} - py${{ matrix.python-version }})'
          report-suffix: 'unit-${{ matrix.python-version }}-${{ matrix.os }}'
